tasks:
  - init: ./gradlew clean build
    command: echo 'starting build'
  - name: server run
    init: docker-compose pull
    command: "docker-compose up -d && docker-compose logs -f"
#  - name: batch pull
#    init: docker-compose -f config/docker-compose
ports:
  - port: 8083
    onOpen: open-preview
    visibility: public
  - port: 8091
    onOpen: open-browser
    visibility: public
  - port: 27017
    onOpen: ignore
    visibility: private

github:
  prebuilds:
    master: true
    addComment: true

