image:
  file: Dockerfile
tasks:
  - command: "./memuser/launch.sh"
  - command: "echo hello terminal world"
  - command: "/usr/local/bin/docker-entrypoint.sh mongod"
  - command: "./synconsole/launch.sh"
ports:
  - port: 8080
    onOpen: open-preview
