image:
  file: Dockerfile
tasks:
  - command: "exec java -jar policyconsole-0.6.1-SNAPSHOT.jar"
  - command: "echo hello terminal world"
  - command: "exec /usr/local/bin/docker-entrypoint.sh mongod"

