image: gclayburg/synconsolegitpod:0.7.5
#image: gclayburg/gitpodmongo:4.1.9
#  file: Dockerfile
tasks:
  - command: "export JAVA_OPTS='-Xmx128m -XX:TieredStopAtLevel=1 -noverify' && /home/gitpod/memuser/run.sh --server.port=8092"
  - command: "echo hello terminal world"
  - command: "/usr/local/bin/docker-entrypoint.sh mongod"
  - command: "export JAVA_OPTS='-Xmx1024m -XX:TieredStopAtLevel=1 -noverify' && /home/gitpod/synconsole/run.sh --server.port=8080 --spring.config.location=$(pwd)/synconsole/ --policy.groovy-home=$(pwd)/src/main/groovy"
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8092
    onOpen: open-browser
  - port: 27017
    onOpen: ignore

